language: android
android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - extra-android-support
before_script:
  - chmod +x gradlew
script:
  - "./gradlew assembleRelease"